//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonFiles.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonFiles.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Format_DashboardTitle {
            get {
                return ResourceManager.GetString("Format_DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilkommen!.
        /// </summary>
        public static string Format_Header {
            get {
                return ResourceManager.GetString("Format_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string label_CPU {
            get {
                return ResourceManager.GetString("label_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Belastung.
        /// </summary>
        public static string label_CPULoad {
            get {
                return ResourceManager.GetString("label_CPULoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker.
        /// </summary>
        public static string label_Docker {
            get {
                return ResourceManager.GetString("label_Docker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt am .
        /// </summary>
        public static string label_Docker_created {
            get {
                return ResourceManager.GetString("label_Docker_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string label_Docker_ID {
            get {
                return ResourceManager.GetString("label_Docker_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string label_Docker_image {
            get {
                return ResourceManager.GetString("label_Docker_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string label_Docker_Name {
            get {
                return ResourceManager.GetString("label_Docker_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports.
        /// </summary>
        public static string label_Docker_ports {
            get {
                return ResourceManager.GetString("label_Docker_ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string label_Docker_status {
            get {
                return ResourceManager.GetString("label_Docker_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string label_Name {
            get {
                return ResourceManager.GetString("label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netzwerk.
        /// </summary>
        public static string label_Network {
            get {
                return ResourceManager.GetString("label_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string label_Network_port {
            get {
                return ResourceManager.GetString("label_Network_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports.
        /// </summary>
        public static string label_Network_Ports {
            get {
                return ResourceManager.GetString("label_Network_Ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prozess.
        /// </summary>
        public static string label_Network_process {
            get {
                return ResourceManager.GetString("label_Network_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokoll.
        /// </summary>
        public static string label_Network_protocol {
            get {
                return ResourceManager.GetString("label_Network_protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        public static string label_PID {
            get {
                return ResourceManager.GetString("label_PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitspeicher.
        /// </summary>
        public static string label_RAM {
            get {
                return ResourceManager.GetString("label_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitspeicher frei, Mb.
        /// </summary>
        public static string label_RAM_free {
            get {
                return ResourceManager.GetString("label_RAM_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitspeicher, Mb.
        /// </summary>
        public static string label_RAM_total {
            get {
                return ResourceManager.GetString("label_RAM_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitspeicher in Verwendung, Mb.
        /// </summary>
        public static string label_RAM_Used {
            get {
                return ResourceManager.GetString("label_RAM_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arbeitspeicher Belastung.
        /// </summary>
        public static string label_RAMLoad {
            get {
                return ResourceManager.GetString("label_RAMLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filesystem.
        /// </summary>
        public static string label_SD_filesystem {
            get {
                return ResourceManager.GetString("label_SD_filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb frei.
        /// </summary>
        public static string label_SD_free {
            get {
                return ResourceManager.GetString("label_SD_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad.
        /// </summary>
        public static string label_SD_mount {
            get {
                return ResourceManager.GetString("label_SD_mount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string label_SD_percent {
            get {
                return ResourceManager.GetString("label_SD_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groß, Mb.
        /// </summary>
        public static string label_SD_size {
            get {
                return ResourceManager.GetString("label_SD_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verw. Mb.
        /// </summary>
        public static string label_SD_used {
            get {
                return ResourceManager.GetString("label_SD_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Kard.
        /// </summary>
        public static string label_SDCard_header {
            get {
                return ResourceManager.GetString("label_SDCard_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dienstleistungen.
        /// </summary>
        public static string label_Services {
            get {
                return ResourceManager.GetString("label_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string label_services_name {
            get {
                return ResourceManager.GetString("label_services_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string label_services_port {
            get {
                return ResourceManager.GetString("label_services_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status des Port.
        /// </summary>
        public static string label_services_portStatus {
            get {
                return ResourceManager.GetString("label_services_portStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string label_services_status {
            get {
                return ResourceManager.GetString("label_services_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stärkste CPU Belastung.
        /// </summary>
        public static string label_Top5CPUProc {
            get {
                return ResourceManager.GetString("label_Top5CPUProc", resourceCulture);
            }
        }
    }
}
