// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Logger.Models;

public partial class Log
{
    public long Id { get; set; }

    public string Application { get; set; }

    public string Text { get; set; }

    public string User { get; set; }

    public string Comment { get; set; }

    public DateTime TimeStamp { get; set; }
}