// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Logger.Models;

public partial class LogError
{
    public long Id { get; set; }

    public string LogLevel { get; set; }

    public string Application { get; set; }

    public string File { get; set; }

    public string Function { get; set; }

    public string Text { get; set; }

    public string StackTrace { get; set; }

    public string Comment { get; set; }

    public int LineNumber { get; set; }

    public DateTime TimeStamp { get; set; }
}