// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Logger.Models;

public partial class LoggingContext : DbContext
{
    public LoggingContext(DbContextOptions<LoggingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Log> Log { get; set; }

    public virtual DbSet<LogError> LogError { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Log>(entity =>
        {
            entity.HasKey(e => new { e.Id, e.Application, e.Text, e.User }).HasName("Log_pkey");

            entity.ToTable("Log", "Logging");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .UseIdentityAlwaysColumn()
                .HasColumnName("ID");
        });

        modelBuilder.Entity<LogError>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("LogEntries_pkey");

            entity.ToTable("LogError", "Logging");

            entity.Property(e => e.Id)
                .UseIdentityAlwaysColumn()
                .HasColumnName("ID");
            entity.Property(e => e.Application).IsRequired();
            entity.Property(e => e.LogLevel).IsRequired();
            entity.Property(e => e.Text).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}