//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaspberryDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaspberryDashboard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wilkommen! Your IP is {0}. Now is {1}.
        /// </summary>
        public static string Format_DashboardTitle {
            get {
                return ResourceManager.GetString("Format_DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dashboard {0}.
        /// </summary>
        public static string Format_Header {
            get {
                return ResourceManager.GetString("Format_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Update System Info at {0}.
        /// </summary>
        public static string Format_LastUpdate_Proc {
            get {
                return ResourceManager.GetString("Format_LastUpdate_Proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Update Services Info at {0}.
        /// </summary>
        public static string Format_LastUpdate_Services {
            get {
                return ResourceManager.GetString("Format_LastUpdate_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPU.
        /// </summary>
        public static string label_CPU {
            get {
                return ResourceManager.GetString("label_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPU Belastung.
        /// </summary>
        public static string label_CPULoad {
            get {
                return ResourceManager.GetString("label_CPULoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Docker.
        /// </summary>
        public static string label_Docker {
            get {
                return ResourceManager.GetString("label_Docker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Erstellt am .
        /// </summary>
        public static string label_Docker_created {
            get {
                return ResourceManager.GetString("label_Docker_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID.
        /// </summary>
        public static string label_Docker_ID {
            get {
                return ResourceManager.GetString("label_Docker_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image.
        /// </summary>
        public static string label_Docker_image {
            get {
                return ResourceManager.GetString("label_Docker_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string label_Docker_Name {
            get {
                return ResourceManager.GetString("label_Docker_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ports.
        /// </summary>
        public static string label_Docker_ports {
            get {
                return ResourceManager.GetString("label_Docker_ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string label_Docker_status {
            get {
                return ResourceManager.GetString("label_Docker_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string label_Name {
            get {
                return ResourceManager.GetString("label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Netzwerk.
        /// </summary>
        public static string label_Network {
            get {
                return ResourceManager.GetString("label_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        public static string label_Network_port {
            get {
                return ResourceManager.GetString("label_Network_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ports.
        /// </summary>
        public static string label_Network_Ports {
            get {
                return ResourceManager.GetString("label_Network_Ports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prozess.
        /// </summary>
        public static string label_Network_process {
            get {
                return ResourceManager.GetString("label_Network_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protokoll.
        /// </summary>
        public static string label_Network_protocol {
            get {
                return ResourceManager.GetString("label_Network_protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PID.
        /// </summary>
        public static string label_PID {
            get {
                return ResourceManager.GetString("label_PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arbeitspeicher.
        /// </summary>
        public static string label_RAM {
            get {
                return ResourceManager.GetString("label_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arbeitspeicher frei, Mb.
        /// </summary>
        public static string label_RAM_free {
            get {
                return ResourceManager.GetString("label_RAM_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arbeitspeicher, Mb.
        /// </summary>
        public static string label_RAM_total {
            get {
                return ResourceManager.GetString("label_RAM_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arbeitspeicher in Verwendung, Mb.
        /// </summary>
        public static string label_RAM_Used {
            get {
                return ResourceManager.GetString("label_RAM_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arbeitspeicher Belastung.
        /// </summary>
        public static string label_RAMLoad {
            get {
                return ResourceManager.GetString("label_RAMLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filesystem.
        /// </summary>
        public static string label_SD_filesystem {
            get {
                return ResourceManager.GetString("label_SD_filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mb frei.
        /// </summary>
        public static string label_SD_free {
            get {
                return ResourceManager.GetString("label_SD_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pfad.
        /// </summary>
        public static string label_SD_mount {
            get {
                return ResourceManager.GetString("label_SD_mount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %.
        /// </summary>
        public static string label_SD_percent {
            get {
                return ResourceManager.GetString("label_SD_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Groß, Mb.
        /// </summary>
        public static string label_SD_size {
            get {
                return ResourceManager.GetString("label_SD_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на verw. Mb.
        /// </summary>
        public static string label_SD_used {
            get {
                return ResourceManager.GetString("label_SD_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SD Kard.
        /// </summary>
        public static string label_SDCard_header {
            get {
                return ResourceManager.GetString("label_SDCard_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dienstleistungen.
        /// </summary>
        public static string label_Services {
            get {
                return ResourceManager.GetString("label_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string label_services_name {
            get {
                return ResourceManager.GetString("label_services_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        public static string label_services_port {
            get {
                return ResourceManager.GetString("label_services_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status des Port.
        /// </summary>
        public static string label_services_portStatus {
            get {
                return ResourceManager.GetString("label_services_portStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string label_services_status {
            get {
                return ResourceManager.GetString("label_services_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stärkste CPU Belastung.
        /// </summary>
        public static string label_Top5CPUProc {
            get {
                return ResourceManager.GetString("label_Top5CPUProc", resourceCulture);
            }
        }
    }
}
